name: gpu

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test-moonshot:
    env:
      CUDA_VISIBLE_DEVICES: 1
      JULIA_DEPOT_PATH: /scratch/github-actions/julia_depot_madipm
    runs-on: self-hosted
    strategy:
      matrix:
        os: [ubuntu-24.04]
        julia-version: ['lts', '1']
        julia-arch: [x64]
        hsl-version: ['2024.11.28']

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/julia-buildpkg@latest
      - name: Set HSL_VERSION as environment variable
        run: echo "HSL_VERSION=${{ matrix.hsl-version }}" >> $GITHUB_ENV
      - name: Install HSL_jll.jl
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.activate(".")
          path_HSL_jll = "/scratch/github-actions/actions_runner_madnlphsl/HSL_jll.jl.v" * ENV["HSL_VERSION"]
          Pkg.develop(path=path_HSL_jll)
      - name: Test MadIPM.jl on CPU
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.develop(path=".")
          Pkg.test("MadIPM")
      - name: Test MadIPM.jl on GPU
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.activate("./scripts")
          Pkg.develop(path=".")
          path_HSL_jll = "/scratch/github-actions/actions_runner_madnlphsl/HSL_jll.jl.v" * ENV["HSL_VERSION"]
          Pkg.develop(path=path_HSL_jll)
          include("/scratch/github-actions/actions_runner_madipm/_work/MadIPM.jl/MadIPM.jl/scripts/test_gpu.jl")
